// Auto-generated by training data pipeline — DO NOT EDIT MANUALLY
// run_id: 2026-03-02-auto-080532
export { CURRICULUMS, getCurriculumById, CURRICULUM_ICONS, getRecommendedCurriculum }
  from './v2026-03-02-auto-080532/curriculum';
