// Auto-generated by training data pipeline — DO NOT EDIT MANUALLY
// Switch controlled by pipeline Step 6

export { TRAINING_CURRICULA, PIPELINE_META } from './v2026-03-01-auto-1228/curriculum';

// Seed data consumed by app runtime (academy, detail, recommendation, analysis)
export { CURRICULUMS, getCurriculumById, CURRICULUM_ICONS, getRecommendedCurriculum } from './v2026-03-01-seed/curriculum';
