// Auto-generated by training data pipeline
// run_id: 2026-03-01-auto-1228
// generated_at: 2026-03-01T12:29:31.416537+09:00
// DO NOT EDIT MANUALLY

export interface TrainingSource {
  source_hash: string;
  title: string;
  domain: string;
  summary: string;
  credibility_score: number;
  source_url: string;
}

export interface CurriculumDay {
  day: number;
  focus: string;
  steps: string[];
  sources: TrainingSource[];
}

export interface Curriculum {
  id: string;
  title: string;
  topic: string;
  days: CurriculumDay[];
}

export const TRAINING_CURRICULA: Curriculum[] = [
  {
    id: "positive_reinforcement",
    title: "Positive Reinforcement Training",
    topic: "positive_reinforcement",
    days: [
    {
        "day": 1,
        "focus": "Day 1: Introduce reward marker (clicker or verbal)",
        "steps": [
            "Introduce reward marker (clicker or verbal)",
            "Teach sit with lure-fade",
            "Reward timing drill: treat within 1s"
        ],
        "sources": [
            {
                "source_hash": "00fabe0b4177",
                "title": "Positive Training | Positively.com",
                "domain": "positively.com",
                "summary": "Victoria Stilwell's positive training philosophy: focus on bond-building, enrichment, two-quadrant approach (R+ and P-).",
                "credibility_score": 72,
                "source_url": "https://positively.com/dog-training/article/philosophy-positive-training"
            },
            {
                "source_hash": "a5dfef1c61be",
                "title": "Improving dog training methods: Efficacy and efficiency of reward and mixed training methods",
                "domain": "pmc.ncbi.nlm.nih.gov",
                "summary": "Peer-reviewed study comparing reward-based vs mixed training methods. Reward-based methods showed higher efficacy and we",
                "credibility_score": 91,
                "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7895348/"
            }
        ]
    },
    {
        "day": 2,
        "focus": "Day 2: Add duration to sit",
        "steps": [
            "Add duration to sit",
            "Introduce down with lure",
            "Practice 5-second stay"
        ],
        "sources": [
            {
                "source_hash": "00fabe0b4177",
                "title": "Positive Training | Positively.com",
                "domain": "positively.com",
                "summary": "Victoria Stilwell's positive training philosophy: focus on bond-building, enrichment, two-quadrant approach (R+ and P-).",
                "credibility_score": 72,
                "source_url": "https://positively.com/dog-training/article/philosophy-positive-training"
            },
            {
                "source_hash": "a5dfef1c61be",
                "title": "Improving dog training methods: Efficacy and efficiency of reward and mixed training methods",
                "domain": "pmc.ncbi.nlm.nih.gov",
                "summary": "Peer-reviewed study comparing reward-based vs mixed training methods. Reward-based methods showed higher efficacy and we",
                "credibility_score": 91,
                "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7895348/"
            }
        ]
    },
    {
        "day": 3,
        "focus": "Day 3: Generalise sit/down to 2 new locations",
        "steps": [
            "Generalise sit/down to 2 new locations",
            "Introduce recall with high-value treat",
            "Shape simple trick (paw)"
        ],
        "sources": [
            {
                "source_hash": "00fabe0b4177",
                "title": "Positive Training | Positively.com",
                "domain": "positively.com",
                "summary": "Victoria Stilwell's positive training philosophy: focus on bond-building, enrichment, two-quadrant approach (R+ and P-).",
                "credibility_score": 72,
                "source_url": "https://positively.com/dog-training/article/philosophy-positive-training"
            },
            {
                "source_hash": "a5dfef1c61be",
                "title": "Improving dog training methods: Efficacy and efficiency of reward and mixed training methods",
                "domain": "pmc.ncbi.nlm.nih.gov",
                "summary": "Peer-reviewed study comparing reward-based vs mixed training methods. Reward-based methods showed higher efficacy and we",
                "credibility_score": 91,
                "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7895348/"
            }
        ]
    },
    {
        "day": 4,
        "focus": "Day 4: Proof sit in mild distraction",
        "steps": [
            "Proof sit in mild distraction",
            "Add stand command",
            "Review and reinforce all learned behaviors"
        ],
        "sources": [
            {
                "source_hash": "00fabe0b4177",
                "title": "Positive Training | Positively.com",
                "domain": "positively.com",
                "summary": "Victoria Stilwell's positive training philosophy: focus on bond-building, enrichment, two-quadrant approach (R+ and P-).",
                "credibility_score": 72,
                "source_url": "https://positively.com/dog-training/article/philosophy-positive-training"
            },
            {
                "source_hash": "a5dfef1c61be",
                "title": "Improving dog training methods: Efficacy and efficiency of reward and mixed training methods",
                "domain": "pmc.ncbi.nlm.nih.gov",
                "summary": "Peer-reviewed study comparing reward-based vs mixed training methods. Reward-based methods showed higher efficacy and we",
                "credibility_score": 91,
                "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7895348/"
            }
        ]
    },
    {
        "day": 5,
        "focus": "Day 5: Introduce leave-it with low-value item",
        "steps": [
            "Introduce leave-it with low-value item",
            "Practice 3D generalisation: duration/distance/distraction",
            "Free-shaping session 5 min"
        ],
        "sources": [
            {
                "source_hash": "00fabe0b4177",
                "title": "Positive Training | Positively.com",
                "domain": "positively.com",
                "summary": "Victoria Stilwell's positive training philosophy: focus on bond-building, enrichment, two-quadrant approach (R+ and P-).",
                "credibility_score": 72,
                "source_url": "https://positively.com/dog-training/article/philosophy-positive-training"
            },
            {
                "source_hash": "a5dfef1c61be",
                "title": "Improving dog training methods: Efficacy and efficiency of reward and mixed training methods",
                "domain": "pmc.ncbi.nlm.nih.gov",
                "summary": "Peer-reviewed study comparing reward-based vs mixed training methods. Reward-based methods showed higher efficacy and we",
                "credibility_score": 91,
                "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7895348/"
            }
        ]
    },
    {
        "day": 6,
        "focus": "Day 6: Reinforce recall with long line",
        "steps": [
            "Reinforce recall with long line",
            "Practice leave-it with high-value item",
            "Low-distraction obedience sequence"
        ],
        "sources": [
            {
                "source_hash": "00fabe0b4177",
                "title": "Positive Training | Positively.com",
                "domain": "positively.com",
                "summary": "Victoria Stilwell's positive training philosophy: focus on bond-building, enrichment, two-quadrant approach (R+ and P-).",
                "credibility_score": 72,
                "source_url": "https://positively.com/dog-training/article/philosophy-positive-training"
            },
            {
                "source_hash": "a5dfef1c61be",
                "title": "Improving dog training methods: Efficacy and efficiency of reward and mixed training methods",
                "domain": "pmc.ncbi.nlm.nih.gov",
                "summary": "Peer-reviewed study comparing reward-based vs mixed training methods. Reward-based methods showed higher efficacy and we",
                "credibility_score": 91,
                "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7895348/"
            }
        ]
    },
    {
        "day": 7,
        "focus": "Day 7: Add heel position introduction",
        "steps": [
            "Add heel position introduction",
            "Review all behaviors in sequence",
            "Session debrief and next week plan"
        ],
        "sources": [
            {
                "source_hash": "00fabe0b4177",
                "title": "Positive Training | Positively.com",
                "domain": "positively.com",
                "summary": "Victoria Stilwell's positive training philosophy: focus on bond-building, enrichment, two-quadrant approach (R+ and P-).",
                "credibility_score": 72,
                "source_url": "https://positively.com/dog-training/article/philosophy-positive-training"
            },
            {
                "source_hash": "a5dfef1c61be",
                "title": "Improving dog training methods: Efficacy and efficiency of reward and mixed training methods",
                "domain": "pmc.ncbi.nlm.nih.gov",
                "summary": "Peer-reviewed study comparing reward-based vs mixed training methods. Reward-based methods showed higher efficacy and we",
                "credibility_score": 91,
                "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7895348/"
            }
        ]
    }
],
  },
  {
    id: "loose_leash_walking",
    title: "Loose Leash Walking",
    topic: "loose_leash_walking",
    days: [
    {
        "day": 1,
        "focus": "Day 1: Fit front-clip harness correctly",
        "steps": [
            "Fit front-clip harness correctly",
            "Teach leash-check-in: reward eye contact",
            "Practice stop-on-tension in yard"
        ],
        "sources": [
            {
                "source_hash": "1952e741fe8b",
                "title": "Training Tips: Loose Leash Walking - San Diego Humane Society",
                "domain": "resources.sdhumane.org",
                "summary": "SD Humane Society protocol: Red Light/Green Light (stop when pull, go when loose), reward check-ins, consistent cue, fro",
                "credibility_score": 80,
                "source_url": "https://resources.sdhumane.org/Resource_Center/Behavior_and_Training/Dogs_and_Puppies/Training_Should_Be_Fun/Training_Tips:_Loose_Leash_Walking"
            },
            {
                "source_hash": "1c97b381c714",
                "title": "Stop a Dog From Pulling on Leash | Best Friends Animal Society",
                "domain": "bestfriends.org",
                "summary": "Best Friends protocol: mark and reward loose leash moments, direction changes as negative punishment, management tools (",
                "credibility_score": 79,
                "source_url": "https://bestfriends.org/pet-care-resources/how-stop-dog-pulling-leash"
            }
        ]
    },
    {
        "day": 2,
        "focus": "Day 2: Red Light/Green Light: stop the moment leash tightens",
        "steps": [
            "Red Light/Green Light: stop the moment leash tightens",
            "Walk 3 minutes with no tension goal",
            "Reward 5 loose-leash moments"
        ],
        "sources": [
            {
                "source_hash": "1952e741fe8b",
                "title": "Training Tips: Loose Leash Walking - San Diego Humane Society",
                "domain": "resources.sdhumane.org",
                "summary": "SD Humane Society protocol: Red Light/Green Light (stop when pull, go when loose), reward check-ins, consistent cue, fro",
                "credibility_score": 80,
                "source_url": "https://resources.sdhumane.org/Resource_Center/Behavior_and_Training/Dogs_and_Puppies/Training_Should_Be_Fun/Training_Tips:_Loose_Leash_Walking"
            },
            {
                "source_hash": "1c97b381c714",
                "title": "Stop a Dog From Pulling on Leash | Best Friends Animal Society",
                "domain": "bestfriends.org",
                "summary": "Best Friends protocol: mark and reward loose leash moments, direction changes as negative punishment, management tools (",
                "credibility_score": 79,
                "source_url": "https://bestfriends.org/pet-care-resources/how-stop-dog-pulling-leash"
            }
        ]
    },
    {
        "day": 3,
        "focus": "Day 3: Add verbal cue 'with me' for heel position check-in",
        "steps": [
            "Add verbal cue 'with me' for heel position check-in",
            "Practice in low-distraction environment",
            "Walk 5 minutes continuous"
        ],
        "sources": [
            {
                "source_hash": "1952e741fe8b",
                "title": "Training Tips: Loose Leash Walking - San Diego Humane Society",
                "domain": "resources.sdhumane.org",
                "summary": "SD Humane Society protocol: Red Light/Green Light (stop when pull, go when loose), reward check-ins, consistent cue, fro",
                "credibility_score": 80,
                "source_url": "https://resources.sdhumane.org/Resource_Center/Behavior_and_Training/Dogs_and_Puppies/Training_Should_Be_Fun/Training_Tips:_Loose_Leash_Walking"
            },
            {
                "source_hash": "1c97b381c714",
                "title": "Stop a Dog From Pulling on Leash | Best Friends Animal Society",
                "domain": "bestfriends.org",
                "summary": "Best Friends protocol: mark and reward loose leash moments, direction changes as negative punishment, management tools (",
                "credibility_score": 79,
                "source_url": "https://bestfriends.org/pet-care-resources/how-stop-dog-pulling-leash"
            }
        ]
    },
    {
        "day": 4,
        "focus": "Day 4: Practice in slightly distracting environment",
        "steps": [
            "Practice in slightly distracting environment",
            "Introduce direction change to interrupt pulling",
            "3 sets of 5-minute walks"
        ],
        "sources": [
            {
                "source_hash": "1952e741fe8b",
                "title": "Training Tips: Loose Leash Walking - San Diego Humane Society",
                "domain": "resources.sdhumane.org",
                "summary": "SD Humane Society protocol: Red Light/Green Light (stop when pull, go when loose), reward check-ins, consistent cue, fro",
                "credibility_score": 80,
                "source_url": "https://resources.sdhumane.org/Resource_Center/Behavior_and_Training/Dogs_and_Puppies/Training_Should_Be_Fun/Training_Tips:_Loose_Leash_Walking"
            },
            {
                "source_hash": "1c97b381c714",
                "title": "Stop a Dog From Pulling on Leash | Best Friends Animal Society",
                "domain": "bestfriends.org",
                "summary": "Best Friends protocol: mark and reward loose leash moments, direction changes as negative punishment, management tools (",
                "credibility_score": 79,
                "source_url": "https://bestfriends.org/pet-care-resources/how-stop-dog-pulling-leash"
            }
        ]
    },
    {
        "day": 5,
        "focus": "Day 5: Walk on busy street with treats ready",
        "steps": [
            "Walk on busy street with treats ready",
            "Reinforce every check-in generously",
            "Goal: 80% loose-leash ratio"
        ],
        "sources": [
            {
                "source_hash": "1952e741fe8b",
                "title": "Training Tips: Loose Leash Walking - San Diego Humane Society",
                "domain": "resources.sdhumane.org",
                "summary": "SD Humane Society protocol: Red Light/Green Light (stop when pull, go when loose), reward check-ins, consistent cue, fro",
                "credibility_score": 80,
                "source_url": "https://resources.sdhumane.org/Resource_Center/Behavior_and_Training/Dogs_and_Puppies/Training_Should_Be_Fun/Training_Tips:_Loose_Leash_Walking"
            },
            {
                "source_hash": "1c97b381c714",
                "title": "Stop a Dog From Pulling on Leash | Best Friends Animal Society",
                "domain": "bestfriends.org",
                "summary": "Best Friends protocol: mark and reward loose leash moments, direction changes as negative punishment, management tools (",
                "credibility_score": 79,
                "source_url": "https://bestfriends.org/pet-care-resources/how-stop-dog-pulling-leash"
            }
        ]
    },
    {
        "day": 6,
        "focus": "Day 6: Introduce stop-and-sniff as reward for loose leash",
        "steps": [
            "Introduce stop-and-sniff as reward for loose leash",
            "Practice long-line recall as enrichment",
            "Review and adjust harness fit"
        ],
        "sources": [
            {
                "source_hash": "1952e741fe8b",
                "title": "Training Tips: Loose Leash Walking - San Diego Humane Society",
                "domain": "resources.sdhumane.org",
                "summary": "SD Humane Society protocol: Red Light/Green Light (stop when pull, go when loose), reward check-ins, consistent cue, fro",
                "credibility_score": 80,
                "source_url": "https://resources.sdhumane.org/Resource_Center/Behavior_and_Training/Dogs_and_Puppies/Training_Should_Be_Fun/Training_Tips:_Loose_Leash_Walking"
            },
            {
                "source_hash": "1c97b381c714",
                "title": "Stop a Dog From Pulling on Leash | Best Friends Animal Society",
                "domain": "bestfriends.org",
                "summary": "Best Friends protocol: mark and reward loose leash moments, direction changes as negative punishment, management tools (",
                "credibility_score": 79,
                "source_url": "https://bestfriends.org/pet-care-resources/how-stop-dog-pulling-leash"
            }
        ]
    },
    {
        "day": 7,
        "focus": "Day 7: Consolidate: 15-minute loose-leash walk with one direction change only",
        "steps": [
            "Consolidate: 15-minute loose-leash walk with one direction change only",
            "Document pass/fail ratio",
            "Graduate to maintenance phase"
        ],
        "sources": [
            {
                "source_hash": "1952e741fe8b",
                "title": "Training Tips: Loose Leash Walking - San Diego Humane Society",
                "domain": "resources.sdhumane.org",
                "summary": "SD Humane Society protocol: Red Light/Green Light (stop when pull, go when loose), reward check-ins, consistent cue, fro",
                "credibility_score": 80,
                "source_url": "https://resources.sdhumane.org/Resource_Center/Behavior_and_Training/Dogs_and_Puppies/Training_Should_Be_Fun/Training_Tips:_Loose_Leash_Walking"
            },
            {
                "source_hash": "1c97b381c714",
                "title": "Stop a Dog From Pulling on Leash | Best Friends Animal Society",
                "domain": "bestfriends.org",
                "summary": "Best Friends protocol: mark and reward loose leash moments, direction changes as negative punishment, management tools (",
                "credibility_score": 79,
                "source_url": "https://bestfriends.org/pet-care-resources/how-stop-dog-pulling-leash"
            }
        ]
    }
],
  },
  {
    id: "separation_anxiety",
    title: "Separation Anxiety Protocol",
    topic: "separation_anxiety",
    days: [
    {
        "day": 1,
        "focus": "Day 1: Assess baseline anxiety signs (pacing, panting, whining)",
        "steps": [
            "Assess baseline anxiety signs (pacing, panting, whining)",
            "Identify predeparture cues that trigger anxiety",
            "Begin predeparture cue neutralisation"
        ],
        "sources": [
            {
                "source_hash": "580e8c021ea3",
                "title": "How to Train Your Dog to Stay Home Alone - RSPCA",
                "domain": "www.rspca.org.uk",
                "summary": "RSPCA guidance: graduated alone training, independence-building, enrichment, calm departures/arrivals, not reinforcing a",
                "credibility_score": 83,
                "source_url": "https://www.rspca.org.uk/adviceandwelfare/pets/dogs/training/leftalone"
            },
            {
                "source_hash": "c427547e0584",
                "title": "Protocol for Understanding and Treating Dogs with Separation Anxiety (Karen Overall)",
                "domain": "www.karenoverall.com",
                "summary": "Dr. Karen Overall's clinical protocol for canine separation anxiety: behavioral assessment, systematic desensitization p",
                "credibility_score": 90,
                "source_url": "https://www.karenoverall.com/wp-content/uploads/2020/06/Protocol-for-understanding-treating-dogs-with-separation-anxiety_Overall.pdf"
            }
        ]
    },
    {
        "day": 2,
        "focus": "Day 2: Practice picking up keys and sitting down (no leaving)",
        "steps": [
            "Practice picking up keys and sitting down (no leaving)",
            "Desensitise coat/bag without departure",
            "Log dog's resting state before/after"
        ],
        "sources": [
            {
                "source_hash": "580e8c021ea3",
                "title": "How to Train Your Dog to Stay Home Alone - RSPCA",
                "domain": "www.rspca.org.uk",
                "summary": "RSPCA guidance: graduated alone training, independence-building, enrichment, calm departures/arrivals, not reinforcing a",
                "credibility_score": 83,
                "source_url": "https://www.rspca.org.uk/adviceandwelfare/pets/dogs/training/leftalone"
            },
            {
                "source_hash": "c427547e0584",
                "title": "Protocol for Understanding and Treating Dogs with Separation Anxiety (Karen Overall)",
                "domain": "www.karenoverall.com",
                "summary": "Dr. Karen Overall's clinical protocol for canine separation anxiety: behavioral assessment, systematic desensitization p",
                "credibility_score": 90,
                "source_url": "https://www.karenoverall.com/wp-content/uploads/2020/06/Protocol-for-understanding-treating-dogs-with-separation-anxiety_Overall.pdf"
            }
        ]
    },
    {
        "day": 3,
        "focus": "Day 3: First absences: 5 seconds out of sight",
        "steps": [
            "First absences: 5 seconds out of sight",
            "Return calmly with no fanfare",
            "Repeat 10x per session"
        ],
        "sources": [
            {
                "source_hash": "580e8c021ea3",
                "title": "How to Train Your Dog to Stay Home Alone - RSPCA",
                "domain": "www.rspca.org.uk",
                "summary": "RSPCA guidance: graduated alone training, independence-building, enrichment, calm departures/arrivals, not reinforcing a",
                "credibility_score": 83,
                "source_url": "https://www.rspca.org.uk/adviceandwelfare/pets/dogs/training/leftalone"
            },
            {
                "source_hash": "c427547e0584",
                "title": "Protocol for Understanding and Treating Dogs with Separation Anxiety (Karen Overall)",
                "domain": "www.karenoverall.com",
                "summary": "Dr. Karen Overall's clinical protocol for canine separation anxiety: behavioral assessment, systematic desensitization p",
                "credibility_score": 90,
                "source_url": "https://www.karenoverall.com/wp-content/uploads/2020/06/Protocol-for-understanding-treating-dogs-with-separation-anxiety_Overall.pdf"
            }
        ]
    },
    {
        "day": 4,
        "focus": "Day 4: Extend to 30-second absences if dog remained calm",
        "steps": [
            "Extend to 30-second absences if dog remained calm",
            "Introduce enrichment toy at door-exit moment",
            "Track regression triggers"
        ],
        "sources": [
            {
                "source_hash": "580e8c021ea3",
                "title": "How to Train Your Dog to Stay Home Alone - RSPCA",
                "domain": "www.rspca.org.uk",
                "summary": "RSPCA guidance: graduated alone training, independence-building, enrichment, calm departures/arrivals, not reinforcing a",
                "credibility_score": 83,
                "source_url": "https://www.rspca.org.uk/adviceandwelfare/pets/dogs/training/leftalone"
            },
            {
                "source_hash": "c427547e0584",
                "title": "Protocol for Understanding and Treating Dogs with Separation Anxiety (Karen Overall)",
                "domain": "www.karenoverall.com",
                "summary": "Dr. Karen Overall's clinical protocol for canine separation anxiety: behavioral assessment, systematic desensitization p",
                "credibility_score": 90,
                "source_url": "https://www.karenoverall.com/wp-content/uploads/2020/06/Protocol-for-understanding-treating-dogs-with-separation-anxiety_Overall.pdf"
            }
        ]
    },
    {
        "day": 5,
        "focus": "Day 5: Extend to 2-minute absences",
        "steps": [
            "Extend to 2-minute absences",
            "Ensure all household members follow same protocol",
            "Address any regression by stepping back one level"
        ],
        "sources": [
            {
                "source_hash": "580e8c021ea3",
                "title": "How to Train Your Dog to Stay Home Alone - RSPCA",
                "domain": "www.rspca.org.uk",
                "summary": "RSPCA guidance: graduated alone training, independence-building, enrichment, calm departures/arrivals, not reinforcing a",
                "credibility_score": 83,
                "source_url": "https://www.rspca.org.uk/adviceandwelfare/pets/dogs/training/leftalone"
            },
            {
                "source_hash": "c427547e0584",
                "title": "Protocol for Understanding and Treating Dogs with Separation Anxiety (Karen Overall)",
                "domain": "www.karenoverall.com",
                "summary": "Dr. Karen Overall's clinical protocol for canine separation anxiety: behavioral assessment, systematic desensitization p",
                "credibility_score": 90,
                "source_url": "https://www.karenoverall.com/wp-content/uploads/2020/06/Protocol-for-understanding-treating-dogs-with-separation-anxiety_Overall.pdf"
            }
        ]
    },
    {
        "day": 6,
        "focus": "Day 6: Extend to 10-minute absences",
        "steps": [
            "Extend to 10-minute absences",
            "Add real-world departure routine",
            "Video-record dog to check for silent distress"
        ],
        "sources": [
            {
                "source_hash": "580e8c021ea3",
                "title": "How to Train Your Dog to Stay Home Alone - RSPCA",
                "domain": "www.rspca.org.uk",
                "summary": "RSPCA guidance: graduated alone training, independence-building, enrichment, calm departures/arrivals, not reinforcing a",
                "credibility_score": 83,
                "source_url": "https://www.rspca.org.uk/adviceandwelfare/pets/dogs/training/leftalone"
            },
            {
                "source_hash": "c427547e0584",
                "title": "Protocol for Understanding and Treating Dogs with Separation Anxiety (Karen Overall)",
                "domain": "www.karenoverall.com",
                "summary": "Dr. Karen Overall's clinical protocol for canine separation anxiety: behavioral assessment, systematic desensitization p",
                "credibility_score": 90,
                "source_url": "https://www.karenoverall.com/wp-content/uploads/2020/06/Protocol-for-understanding-treating-dogs-with-separation-anxiety_Overall.pdf"
            }
        ]
    },
    {
        "day": 7,
        "focus": "Day 7: Consolidate 30-minute alone time",
        "steps": [
            "Consolidate 30-minute alone time",
            "Create alone-time enrichment plan",
            "Review progress and plan professional consult if needed"
        ],
        "sources": [
            {
                "source_hash": "580e8c021ea3",
                "title": "How to Train Your Dog to Stay Home Alone - RSPCA",
                "domain": "www.rspca.org.uk",
                "summary": "RSPCA guidance: graduated alone training, independence-building, enrichment, calm departures/arrivals, not reinforcing a",
                "credibility_score": 83,
                "source_url": "https://www.rspca.org.uk/adviceandwelfare/pets/dogs/training/leftalone"
            },
            {
                "source_hash": "c427547e0584",
                "title": "Protocol for Understanding and Treating Dogs with Separation Anxiety (Karen Overall)",
                "domain": "www.karenoverall.com",
                "summary": "Dr. Karen Overall's clinical protocol for canine separation anxiety: behavioral assessment, systematic desensitization p",
                "credibility_score": 90,
                "source_url": "https://www.karenoverall.com/wp-content/uploads/2020/06/Protocol-for-understanding-treating-dogs-with-separation-anxiety_Overall.pdf"
            }
        ]
    }
],
  },
  {
    id: "reactivity_desensitization",
    title: "Reactivity Desensitization & Counterconditioning",
    topic: "reactivity_desensitization",
    days: [
    {
        "day": 1,
        "focus": "Day 1: Identify specific triggers (dogs, people, bikes, etc.)",
        "steps": [
            "Identify specific triggers (dogs, people, bikes, etc.)",
            "Find threshold distance where dog notices but stays calm",
            "Practice calm marker + treat at threshold 10 reps"
        ],
        "sources": [
            {
                "source_hash": "780273215720",
                "title": "Introduction to Desensitization and Counterconditioning | VCA Animal Hospitals",
                "domain": "vcahospitals.com",
                "summary": "VCA veterinary guide: DS/CC definitions, threshold concept, stimulus gradient, pairing trigger+treat, 5-15min sessions, ",
                "credibility_score": 84,
                "source_url": "https://vcahospitals.com/know-your-pet/introduction-to-desensitization-and-counterconditioning"
            },
            {
                "source_hash": "ff2ee0b350be",
                "title": "Changing Your Dog's Behavior With Desensitization and Counterconditioning - AKC",
                "domain": "www.akc.org",
                "summary": "AKC guide: identify trigger, find threshold distance, controlled below-threshold exposures, gradually increase intensity",
                "credibility_score": 78,
                "source_url": "https://www.akc.org/expert-advice/training/changing-your-dogs-behavior-with-desensitization-and-counter-conditioning/"
            }
        ]
    },
    {
        "day": 2,
        "focus": "Day 2: Set up controlled exposure at threshold minus 20%",
        "steps": [
            "Set up controlled exposure at threshold minus 20%",
            "Pair trigger appearance with high-value treat (BAT/CC)",
            "End session before any reactive response"
        ],
        "sources": [
            {
                "source_hash": "780273215720",
                "title": "Introduction to Desensitization and Counterconditioning | VCA Animal Hospitals",
                "domain": "vcahospitals.com",
                "summary": "VCA veterinary guide: DS/CC definitions, threshold concept, stimulus gradient, pairing trigger+treat, 5-15min sessions, ",
                "credibility_score": 84,
                "source_url": "https://vcahospitals.com/know-your-pet/introduction-to-desensitization-and-counterconditioning"
            },
            {
                "source_hash": "ff2ee0b350be",
                "title": "Changing Your Dog's Behavior With Desensitization and Counterconditioning - AKC",
                "domain": "www.akc.org",
                "summary": "AKC guide: identify trigger, find threshold distance, controlled below-threshold exposures, gradually increase intensity",
                "credibility_score": 78,
                "source_url": "https://www.akc.org/expert-advice/training/changing-your-dogs-behavior-with-desensitization-and-counter-conditioning/"
            }
        ]
    },
    {
        "day": 3,
        "focus": "Day 3: Reduce distance by 5% only if 3 consecutive calm sessions",
        "steps": [
            "Reduce distance by 5% only if 3 consecutive calm sessions",
            "Increase session length to 15 min",
            "Log body language data"
        ],
        "sources": [
            {
                "source_hash": "780273215720",
                "title": "Introduction to Desensitization and Counterconditioning | VCA Animal Hospitals",
                "domain": "vcahospitals.com",
                "summary": "VCA veterinary guide: DS/CC definitions, threshold concept, stimulus gradient, pairing trigger+treat, 5-15min sessions, ",
                "credibility_score": 84,
                "source_url": "https://vcahospitals.com/know-your-pet/introduction-to-desensitization-and-counterconditioning"
            },
            {
                "source_hash": "ff2ee0b350be",
                "title": "Changing Your Dog's Behavior With Desensitization and Counterconditioning - AKC",
                "domain": "www.akc.org",
                "summary": "AKC guide: identify trigger, find threshold distance, controlled below-threshold exposures, gradually increase intensity",
                "credibility_score": 78,
                "source_url": "https://www.akc.org/expert-advice/training/changing-your-dogs-behavior-with-desensitization-and-counter-conditioning/"
            }
        ]
    },
    {
        "day": 4,
        "focus": "Day 4: Practice on walks: u-turn protocol if over threshold",
        "steps": [
            "Practice on walks: u-turn protocol if over threshold",
            "Introduce Look At That (LAT) game",
            "Maintain below-threshold distances"
        ],
        "sources": [
            {
                "source_hash": "780273215720",
                "title": "Introduction to Desensitization and Counterconditioning | VCA Animal Hospitals",
                "domain": "vcahospitals.com",
                "summary": "VCA veterinary guide: DS/CC definitions, threshold concept, stimulus gradient, pairing trigger+treat, 5-15min sessions, ",
                "credibility_score": 84,
                "source_url": "https://vcahospitals.com/know-your-pet/introduction-to-desensitization-and-counterconditioning"
            },
            {
                "source_hash": "ff2ee0b350be",
                "title": "Changing Your Dog's Behavior With Desensitization and Counterconditioning - AKC",
                "domain": "www.akc.org",
                "summary": "AKC guide: identify trigger, find threshold distance, controlled below-threshold exposures, gradually increase intensity",
                "credibility_score": 78,
                "source_url": "https://www.akc.org/expert-advice/training/changing-your-dogs-behavior-with-desensitization-and-counter-conditioning/"
            }
        ]
    },
    {
        "day": 5,
        "focus": "Day 5: Continue distance reduction plan",
        "steps": [
            "Continue distance reduction plan",
            "Add mild distraction variety",
            "Practice in 2 different locations"
        ],
        "sources": [
            {
                "source_hash": "780273215720",
                "title": "Introduction to Desensitization and Counterconditioning | VCA Animal Hospitals",
                "domain": "vcahospitals.com",
                "summary": "VCA veterinary guide: DS/CC definitions, threshold concept, stimulus gradient, pairing trigger+treat, 5-15min sessions, ",
                "credibility_score": 84,
                "source_url": "https://vcahospitals.com/know-your-pet/introduction-to-desensitization-and-counterconditioning"
            },
            {
                "source_hash": "ff2ee0b350be",
                "title": "Changing Your Dog's Behavior With Desensitization and Counterconditioning - AKC",
                "domain": "www.akc.org",
                "summary": "AKC guide: identify trigger, find threshold distance, controlled below-threshold exposures, gradually increase intensity",
                "credibility_score": 78,
                "source_url": "https://www.akc.org/expert-advice/training/changing-your-dogs-behavior-with-desensitization-and-counter-conditioning/"
            }
        ]
    },
    {
        "day": 6,
        "focus": "Day 6: Proof at multiple locations near threshold",
        "steps": [
            "Proof at multiple locations near threshold",
            "Build confidence with parallel walking",
            "Track progress chart"
        ],
        "sources": [
            {
                "source_hash": "780273215720",
                "title": "Introduction to Desensitization and Counterconditioning | VCA Animal Hospitals",
                "domain": "vcahospitals.com",
                "summary": "VCA veterinary guide: DS/CC definitions, threshold concept, stimulus gradient, pairing trigger+treat, 5-15min sessions, ",
                "credibility_score": 84,
                "source_url": "https://vcahospitals.com/know-your-pet/introduction-to-desensitization-and-counterconditioning"
            },
            {
                "source_hash": "ff2ee0b350be",
                "title": "Changing Your Dog's Behavior With Desensitization and Counterconditioning - AKC",
                "domain": "www.akc.org",
                "summary": "AKC guide: identify trigger, find threshold distance, controlled below-threshold exposures, gradually increase intensity",
                "credibility_score": 78,
                "source_url": "https://www.akc.org/expert-advice/training/changing-your-dogs-behavior-with-desensitization-and-counter-conditioning/"
            }
        ]
    },
    {
        "day": 7,
        "focus": "Day 7: Consolidate gains: multiple triggers in managed sequence",
        "steps": [
            "Consolidate gains: multiple triggers in managed sequence",
            "Plan long-term management and generalisation",
            "Consult certified behaviorist if plateau"
        ],
        "sources": [
            {
                "source_hash": "780273215720",
                "title": "Introduction to Desensitization and Counterconditioning | VCA Animal Hospitals",
                "domain": "vcahospitals.com",
                "summary": "VCA veterinary guide: DS/CC definitions, threshold concept, stimulus gradient, pairing trigger+treat, 5-15min sessions, ",
                "credibility_score": 84,
                "source_url": "https://vcahospitals.com/know-your-pet/introduction-to-desensitization-and-counterconditioning"
            },
            {
                "source_hash": "ff2ee0b350be",
                "title": "Changing Your Dog's Behavior With Desensitization and Counterconditioning - AKC",
                "domain": "www.akc.org",
                "summary": "AKC guide: identify trigger, find threshold distance, controlled below-threshold exposures, gradually increase intensity",
                "credibility_score": 78,
                "source_url": "https://www.akc.org/expert-advice/training/changing-your-dogs-behavior-with-desensitization-and-counter-conditioning/"
            }
        ]
    }
],
  },
];

export const PIPELINE_META = { run_id: '2026-03-01-auto-1228', generated_at: '2026-03-01T12:29:31.416537+09:00' };
