/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _LoginRoute } from '../pages/login';
import { Route as _WelcomeRoute } from '../pages/onboarding/welcome';
import { Route as _SurveyRoute } from '../pages/onboarding/survey';
import { Route as _SurveyResultRoute } from '../pages/onboarding/survey-result';
import { Route as _NotificationRoute } from '../pages/onboarding/notification';
import { Route as _DashboardRoute } from '../pages/dashboard/';
import { Route as _QuickLogRoute } from '../pages/dashboard/quick-log';
import { Route as _AnalysisRoute } from '../pages/dashboard/analysis';
import { Route as _CoachingResultRoute } from '../pages/coaching/result';
import { Route as _TrainingAcademyRoute } from '../pages/training/academy';
import { Route as _TrainingDetailRoute } from '../pages/training/detail';
import { Route as _DogProfileRoute } from '../pages/dog/profile';
import { Route as _DogSwitcherRoute } from '../pages/dog/switcher';
import { Route as _DogAddRoute } from '../pages/dog/add';
import { Route as _SettingsRoute } from '../pages/settings/';
import { Route as _SubscriptionRoute } from '../pages/settings/subscription';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/login': (typeof _LoginRoute)['_inputType'];
    '/onboarding/welcome': (typeof _WelcomeRoute)['_inputType'];
    '/onboarding/survey': (typeof _SurveyRoute)['_inputType'];
    '/onboarding/survey-result': (typeof _SurveyResultRoute)['_inputType'];
    '/onboarding/notification': (typeof _NotificationRoute)['_inputType'];
    '/dashboard': (typeof _DashboardRoute)['_inputType'];
    '/dashboard/quick-log': (typeof _QuickLogRoute)['_inputType'];
    '/dashboard/analysis': (typeof _AnalysisRoute)['_inputType'];
    '/coaching/result': (typeof _CoachingResultRoute)['_inputType'];
    '/training/academy': (typeof _TrainingAcademyRoute)['_inputType'];
    '/training/detail': (typeof _TrainingDetailRoute)['_inputType'];
    '/dog/profile': (typeof _DogProfileRoute)['_inputType'];
    '/dog/switcher': (typeof _DogSwitcherRoute)['_inputType'];
    '/dog/add': (typeof _DogAddRoute)['_inputType'];
    '/settings': (typeof _SettingsRoute)['_inputType'];
    '/settings/subscription': (typeof _SubscriptionRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/login': (typeof _LoginRoute)['_outputType'];
    '/onboarding/welcome': (typeof _WelcomeRoute)['_outputType'];
    '/onboarding/survey': (typeof _SurveyRoute)['_outputType'];
    '/onboarding/survey-result': (typeof _SurveyResultRoute)['_outputType'];
    '/onboarding/notification': (typeof _NotificationRoute)['_outputType'];
    '/dashboard': (typeof _DashboardRoute)['_outputType'];
    '/dashboard/quick-log': (typeof _QuickLogRoute)['_outputType'];
    '/dashboard/analysis': (typeof _AnalysisRoute)['_outputType'];
    '/coaching/result': (typeof _CoachingResultRoute)['_outputType'];
    '/training/academy': (typeof _TrainingAcademyRoute)['_outputType'];
    '/training/detail': (typeof _TrainingDetailRoute)['_outputType'];
    '/dog/profile': (typeof _DogProfileRoute)['_outputType'];
    '/dog/switcher': (typeof _DogSwitcherRoute)['_outputType'];
    '/dog/add': (typeof _DogAddRoute)['_outputType'];
    '/settings': (typeof _SettingsRoute)['_outputType'];
    '/settings/subscription': (typeof _SubscriptionRoute)['_outputType'];
  }
}
