/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _CoachingResultRoute } from '../pages/coaching/result';
import { Route as _DashboardAnalysisRoute } from '../pages/dashboard/analysis';
import { Route as _DashboardRoute } from '../pages/dashboard';
import { Route as _DashboardQuickLogRoute } from '../pages/dashboard/quick-log';
import { Route as _DogAddRoute } from '../pages/dog/add';
import { Route as _DogProfileRoute } from '../pages/dog/profile';
import { Route as _DogSwitcherRoute } from '../pages/dog/switcher';
import { Route as _IndexRoute } from '../pages/';
import { Route as _LegalPrivacyRoute } from '../pages/legal/privacy';
import { Route as _LegalTermsRoute } from '../pages/legal/terms';
import { Route as _LoginRoute } from '../pages/login';
import { Route as _OnboardingNotificationRoute } from '../pages/onboarding/notification';
import { Route as _OnboardingSurveyResultRoute } from '../pages/onboarding/survey-result';
import { Route as _OnboardingSurveyRoute } from '../pages/onboarding/survey';
import { Route as _OnboardingWelcomeRoute } from '../pages/onboarding/welcome';
import { Route as _OpsSettingsRoute } from '../pages/ops/settings';
import { Route as _OpsTodayRoute } from '../pages/ops/today';
import { Route as _ParentReportsRoute } from '../pages/parent/reports';
import { Route as _ReportShareTokenRoute } from '../pages/report/[shareToken]';
import { Route as _SettingsRoute } from '../pages/settings';
import { Route as _SettingsSubscriptionRoute } from '../pages/settings/subscription';
import { Route as _TrainingAcademyRoute } from '../pages/training/academy';
import { Route as _TrainingDetailRoute } from '../pages/training/detail';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/coaching/result': (typeof _CoachingResultRoute)['_inputType'];
    '/dashboard/analysis': (typeof _DashboardAnalysisRoute)['_inputType'];
    '/dashboard': (typeof _DashboardRoute)['_inputType'];
    '/dashboard/quick-log': (typeof _DashboardQuickLogRoute)['_inputType'];
    '/dog/add': (typeof _DogAddRoute)['_inputType'];
    '/dog/profile': (typeof _DogProfileRoute)['_inputType'];
    '/dog/switcher': (typeof _DogSwitcherRoute)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
    '/legal/privacy': (typeof _LegalPrivacyRoute)['_inputType'];
    '/legal/terms': (typeof _LegalTermsRoute)['_inputType'];
    '/login': (typeof _LoginRoute)['_inputType'];
    '/onboarding/notification': (typeof _OnboardingNotificationRoute)['_inputType'];
    '/onboarding/survey-result': (typeof _OnboardingSurveyResultRoute)['_inputType'];
    '/onboarding/survey': (typeof _OnboardingSurveyRoute)['_inputType'];
    '/onboarding/welcome': (typeof _OnboardingWelcomeRoute)['_inputType'];
    '/ops/settings': (typeof _OpsSettingsRoute)['_inputType'];
    '/ops/today': (typeof _OpsTodayRoute)['_inputType'];
    '/parent/reports': (typeof _ParentReportsRoute)['_inputType'];
    '/report/[shareToken]': (typeof _ReportShareTokenRoute)['_inputType'];
    '/settings': (typeof _SettingsRoute)['_inputType'];
    '/settings/subscription': (typeof _SettingsSubscriptionRoute)['_inputType'];
    '/training/academy': (typeof _TrainingAcademyRoute)['_inputType'];
    '/training/detail': (typeof _TrainingDetailRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/coaching/result': (typeof _CoachingResultRoute)['_outputType'];
    '/dashboard/analysis': (typeof _DashboardAnalysisRoute)['_outputType'];
    '/dashboard': (typeof _DashboardRoute)['_outputType'];
    '/dashboard/quick-log': (typeof _DashboardQuickLogRoute)['_outputType'];
    '/dog/add': (typeof _DogAddRoute)['_outputType'];
    '/dog/profile': (typeof _DogProfileRoute)['_outputType'];
    '/dog/switcher': (typeof _DogSwitcherRoute)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
    '/legal/privacy': (typeof _LegalPrivacyRoute)['_outputType'];
    '/legal/terms': (typeof _LegalTermsRoute)['_outputType'];
    '/login': (typeof _LoginRoute)['_outputType'];
    '/onboarding/notification': (typeof _OnboardingNotificationRoute)['_outputType'];
    '/onboarding/survey-result': (typeof _OnboardingSurveyResultRoute)['_outputType'];
    '/onboarding/survey': (typeof _OnboardingSurveyRoute)['_outputType'];
    '/onboarding/welcome': (typeof _OnboardingWelcomeRoute)['_outputType'];
    '/ops/settings': (typeof _OpsSettingsRoute)['_outputType'];
    '/ops/today': (typeof _OpsTodayRoute)['_outputType'];
    '/parent/reports': (typeof _ParentReportsRoute)['_outputType'];
    '/report/[shareToken]': (typeof _ReportShareTokenRoute)['_outputType'];
    '/settings': (typeof _SettingsRoute)['_outputType'];
    '/settings/subscription': (typeof _SettingsSubscriptionRoute)['_outputType'];
    '/training/academy': (typeof _TrainingAcademyRoute)['_outputType'];
    '/training/detail': (typeof _TrainingDetailRoute)['_outputType'];
  }
}
